### ISSUE TITLE
Error reading data. Received 0 instead of expected 7 bytes

### ISSUE THREAD

**Issue by arogachev** [videlalvaro/php-amqplib#272]
I'm using Vagrant + puphpet, together with this extension. Recently I updated to the latest versions and now struggling with this issue.

There are some problems with applying configuration (at least for me).
User `guest` was existing by default, but when I tried:

```
sudo rabbitmqctl list_user_permissions guest
```

it says:

```
Listing permissions for user "guest" ...
Error: {no_such_user,<<"guest">>}
```

So I executed these commands manually for testing purposes.

```
sudo rabbitmqctl add_vhost /
sudo rabbitmqctl add_user guest guest // was already existing as default
sudo rabbitmqctl set_permissions -p / guest ".*" ".*" ".*"
```

Now if I execute:

```
sudo rabbitmqctl list_user_permissions guest
```

It gives the following results:

```
Listing permissions for user "guest" ...
/      .*      .*      .*
...done.
```

Then I restarted rabbit server like that:

```
sudo service rabbitmq-server restart
```

Connection is created like that:

```php
$connection = new AMQPConnection('127.0.0.1', 5672, 'guest', 'guest', '/');
```

According to trace, error appears right on this line. Here is full error text:

```
PhpAmqpLib\Exception\AMQPRuntimeException

Error reading data. Received 0 instead of expected 7 bytes
```
    
`puphpet` config rabbitmq section:

```yml
rabbitmq:
    install: '1'
    settings:
        port: '5672'
    users:
        user-1:
            admin: true
            name: admin
            password: admin
            permissions:
                permissions-1:
                    host: /
                    configure_permission: '.*'
                    read_permission: '.*'
                    write_permission: '.*'
    vhosts:
        - /
    plugins: {  }
```

I also tried with `admin` user, the result is the same error.
